name: "Nightly builds of the interchain stack"
on:
  schedule:
      - cron: '0 0 * * *'
  pull_request:
  merge_group:
  push:
    branches:
      - main
      - release/**
permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}-build
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-arch: ["amd64", "arm", "arm64"]
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          check-latest: true
      - name: Build
        run: GOARCH=${{ matrix.go-arch }} make build
